package com.songoda.epicquests.story.quest.action;

public enum ActionType {
    ENTER_REGION, KILL_MYTHIC_MOB, MINE_BLOCK, PICKUP_ITEM, RIGHT_CLICK_BLOCK, RIGHT_CLICK_ENTITY, RIGHT_CLICK_CITIZEN, KILL_ENTITY_TYPE, DROP_ITEM
}
